# Generated by Django 4.1 on 2022-09-20 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.CharField(choices=[('Watched', 'Watched'), ("Haven't Watched", 'Have Not Watched')], default="Haven't Watched", max_length=15)),
                ('title', models.TextField()),
                ('rating', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('release_date', models.DateField()),
                ('review', models.TextField()),
            ],
        ),
    ]
